### ISSUE TITLE
Wrong number of molecules in the data set

### ISSUE THREAD

**Issue by marcelmbn** [grimme-lab/acqm#1]
According to a simple analysis on the directory structure, I find the number of 2532 molecules (i.e., molecule directories) instead of 2537.
```
$ find . -mindepth 2 -maxdepth 2 -type d ! -path "**/.git/**" | wc -l
2532
```

Without excluding the `.git` directory, I end up with 2537 structures. Do I oversee something, or is the number just slightly incorrect due to the (recursive) `.git` directories?

**Comment by marcelmbn** [comment]
As an add-on (if the correction is true): Could you find out how the number of molecules is distributed between _mindless_ and _normal_ structures?

**Comment by lukaswittmann** [comment]
Updated the docs. 
The "correct" distinction between mindless and normal is not unambiguous in retrospect; the small structures (i.e. <9 atoms) are very similar and both computer-generated (once randomly and once with the Architect).
